# Generated by Django 3.1.3 on 2020-11-14 13:59

from django.db import migrations, models
import django.db.models.deletion
import users.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgeResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('russian', models.IntegerField(default=0)),
                ('mathProf', models.IntegerField(default=0)),
                ('mathBase', models.IntegerField(default=0)),
                ('biology', models.IntegerField(default=0)),
                ('informatics', models.IntegerField(default=0)),
                ('socialStudies', models.IntegerField(default=0)),
                ('physics', models.IntegerField(default=0)),
                ('chemistry', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
                ('geography', models.IntegerField(default=0)),
                ('english', models.IntegerField(default=0)),
                ('german', models.IntegerField(default=0)),
                ('french', models.IntegerField(default=0)),
                ('chinese', models.IntegerField(default=0)),
                ('spanish', models.IntegerField(default=0)),
                ('literature', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('password', models.CharField(default=uuid.uuid4, max_length=128, verbose_name='password')),
                ('token', models.TextField(default=uuid.uuid4, unique=True, verbose_name='token')),
                ('first_name', models.CharField(max_length=70, verbose_name='first name')),
                ('last_name', models.CharField(max_length=70, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('ege_results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.egeresults')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
