# Generated by Django 3.1.3 on 2020-11-14 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201114_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ege_results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.egeresults'),
        ),
    ]
