# Generated by Django 3.1.3 on 2020-12-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='status',
            new_name='message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
