# Generated by Django 3.1.3 on 2020-12-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='lon',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
