# Generated by Django 3.1.3 on 2020-12-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_auto_20201213_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edprogram',
            old_name='preview',
            new_name='photo',
        ),
    ]
