# Generated by Django 3.1.3 on 2020-12-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_auto_20201227_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='edprogram',
            name='probability',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edprogram',
            name='probability_number',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
