# Generated by Django 3.1.3 on 2020-12-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_university_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
